language: node_js
node_js:
- '0.10'
deploy:
  provider: heroku
  app: express-example
  clean_up: false
  api_key:
    secure: PoNunpaitVIhafC0RKcHGS7F5d+Di2XXu+Jzxik1nVV7cBEe94ov52wWwRpjZr+muJnx2FiVzh+6KZo9hixT7Ca2xC9bB1Lyw2m6jmh9pS8k6PnzKkzSyRMNUMpvD9+3g3TcKY5EUX/ksW2BPjYC4Rjb+TF1jT3uSVIMwI6jpdM=
