language: node_js
node_js:
- '0.10'
deploy:
  provider: heroku
  app: express-example
  api_key:
    secure: lnB4PYBB7gRRzC2YjmUB0orGqU6IiyJUDE1RB2Bww5+RgcKN5z/W5aaVyfyYLkfG6gOUqEh1WWzM5OPsxdl713pJUhRSW834qkn6SMFlOFI5aX9aBcESOm06XzpcwAm9jTTUUwTsw4PW4SJFgcbyY3Gn1eDn5jUTNp+wiJq/m3BZrub2obiO0WOsINFSU16QF95YP0gmrHMW5Zzt9PZJxlMm2r62jscRfV2l4hs7Ni4U9pi/uV6uRU23Hbx0XBGIiIicpRj1/zf2gP7ryiXTqXCep6x9cMVlarOB4d+vKyo4sYVcF8JUYTkqZ8MlziPrSc43csB5PUVAwQxPpnkm2k9UM3kz/s4Ddk/wE9bhrucQuuIzZTe6fZIKdUNRclwky9IjW0lsS9rDPtdfM3t7wi0jnokrvU3Ki8torAlHOEiNLImxHJD/PpQkOJHGVRKVFRDgIE2q9IaoSFO+DCzam6xoBOZPDtRNclkOwT3NSHEaNfgjjJkUzjgUcq7AWiRKZvIEGAQHu7F9cJPITWVG2jKNBIwGoxpxqwp0V0vlp+1j0EWttSv18kJQg8K5ZLoFIDuqHNofE7DwBBmv1euXxUJzpVJdTokJDNIIG3ym5jjoRvzPeAMjlGghrisV58lyMfmxsnBmNWnJVPJGNLDQSJHUl4x+P5krLYGK5Xl1SyQ=
